// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookmarkletSignController from "./bookmarklet_sign_controller"
application.register("bookmarklet-sign", BookmarkletSignController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NostrAuthController from "./nostr_auth_controller"
application.register("nostr-auth", NostrAuthController)

import NostrSignController from "./nostr_sign_controller"
application.register("nostr-sign", NostrSignController)
